Move 'VF/MAC/VLAN' from NetConf to NetArgs by following the CNI spec
hustcat/sriov-cni pull request #8
Opened 2017-03-07 11:28 UTC by hustcat

Move 'VF/MAC/VLAN' from NetConf to NetArgs by following the [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration).

2017-03-07 11:45 UTC, rkamudhan commented
Hi Yin,

Is it something like below? 
 
```json
{
  "name": "sriov-net",
  "type": "sriov",
  "args": {
    "master": "eth1",
    "vf": 1,
    "mac": "66:d8:02:77:aa:aa"
  },
  "ipam": {
    "type": "host-local",
    // ipam specific
    "subnet": "10.1.0.0/16",
    "gateway": "10.1.0.1"
  },
  "dns": {
    "nameservers": [ "10.1.0.1" ]
  }
}
```

2017-03-07 11:50 UTC, rkamudhan commented on README.md
> +        "type": "fixipam",
Is there any reason to use fixipam?

2017-03-07 11:56 UTC, rkamudhan commented on README.md
>      "master": "eth1",
Can we add a example of Args here. So that user can understand it ?

2017-03-07 11:58 UTC, rkamudhan requested changes
I will test it and let you know asap.

2017-03-07 12:32 UTC, hustcat commented on README.md
> +        "type": "fixipam",
No, any IPAM plugin is OK:)

2017-03-07 12:43 UTC, hustcat commented
@rkamudhan By CNI spec:
Maybe we use `master` as `args` field in [network configuration](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration), and use `VF`，`MAC` etc. as `args` field in [Parameters](https://github.com/containernetworking/cni/blob/master/SPEC.md#parameters)  that for simple configuration on a per-container basis.

2017-03-07 12:49 UTC, hustcat commented
@rkamudhan I am waiting your testing reply :)

2017-03-10 09:40 UTC, rkamudhan commented
@hustcat 
I think, it is better "master" field not added in the args field, I see args as the parameter, which should be optional, without args parameter also SRIOV plugins should work. But without master and ipam, Currently, SRIOV plugin can't work.  Please join in our slack [https://intel-corp.herokuapp.com/](https://intel-corp.herokuapp.com/), I like to discuss with you about our forked version of sriov [https://github.com/Intel-Corp/sriov-cni](https://github.com/Intel-Corp/sriov-cni), we added so many features to your SRIOV plugin.

2017-03-13 03:01 UTC, hustcat commented
@rkamudhan The features you added are so amazing, I'd like to merged it if you like.  [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration) allowed plugin added its own optional fields, so add `master` field is OK. 

But I still wonder how these optional fields to integrated with Kubernetes. see [1](https://groups.google.com/forum/#!topic/kubernetes-sig-network/Ysui_kSJogI), [2](https://docs.google.com/document/d/1TW3P4c8auWwYy-w_5afIPDcGNLK3LZf0m14943eVfVg/edit?ts=58877ea7).

2017-03-13 18:01 UTC, rkamudhan commented
@hustcat , I think CNI Args will be a part of pod spec in kubernetes, which are optional. The .conflist file work similar to the Multus plugin

2017-03-14 07:21 UTC, hustcat commented
@rkamudhan Thanks, I‘ll merged this PR now. After this, let's merge your DPDK and other features:)

2017-03-14 07:21 UTC, merged