Support VF self Management
hustcat/sriov-cni pull request #9
Opened 2017-03-14 08:38 UTC by hustcat

Support VF self Management. Copy from @rkamudhan 's [commit](https://github.com/Intel-Corp/sriov-cni/commit/efba06fb76e7598f3a394e8cfc01ab330520d4ea).

2017-03-14 08:40 UTC, hustcat commented
@rkamudhan I'v made changes from your commit to be compatiable with master branch. Please take a look.

2017-03-14 08:50 UTC, rkamudhan commented
@hustcat I will check the plugin, and let you know by tomorrow.

2017-03-15 11:47 UTC, rkamudhan requested changes
With reference to commit https://github.com/Intel-Corp/sriov-cni/commit/efba06fb76e7598f3a394e8cfc01ab330520d4ea#diff-8becae7a8222be03e1bcd86d9adaa117R115

2017-03-15 11:47 UTC, rkamudhan commented on sriov/sriov.go
> +	vfDevName, err := getVFDeviceName(masterName, vfIdx)
Do we need to call the getVFDeviceName() twice inside the allocFreeVF() function ?

2017-03-15 15:39 UTC, hustcat commented on sriov/sriov.go
> +	vfDevName, err := getVFDeviceName(masterName, vfIdx)
Maybe return device name in `allocFreeVF` is better. what do you think? @rkamudhan

2017-03-16 08:21 UTC, hustcat commented
@rkamudhan Updated, PTAL:)

2017-05-05 03:45 UTC, hustcat commented
@rkamudhan Have you still care this PR?

2017-05-05 08:23 UTC, rkamudhan commented
@hustcat I will review it, in other 2 days and confirm you.

2017-05-09 20:30 UTC, merged

2017-05-09 20:32 UTC, rkamudhan commented
@hustcat merged the code from the Intel repo [https://github.com/Intel-Corp/sriov-cni/commit/efba06fb76e7598f3a394e8cfc01ab330520d4ea](https://github.com/Intel-Corp/sriov-cni/commit/efba06fb76e7598f3a394e8cfc01ab330520d4ea)